# Generated by Django 5.2.5 on 2025-08-29 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('laser_status', models.BooleanField(default=False)),
                ('laser_power', models.FloatField(default=0.0)),
                ('laser_wavelength', models.FloatField(default=532.0)),
                ('laser_calibrated', models.BooleanField(default=False)),
                ('camera_temp', models.FloatField(default=20.0)),
                ('camera_running', models.BooleanField(default=False)),
                ('grating_wavelength', models.FloatField(default=500.0)),
                ('monochromator_wavelength', models.FloatField(default=500.0)),
                ('spectrometer_wavelength', models.FloatField(default=500.0)),
                ('entrance_slit_width', models.FloatField(default=100.0)),
                ('stage_position', models.JSONField(default=dict)),
                ('microscope_mode', models.CharField(choices=[('ramanmode', 'Raman Mode'), ('imagemode', 'Image Mode')], default='ramanmode', max_length=20)),
                ('instrument_ready', models.BooleanField(default=True)),
                ('apply_live_calibration', models.BooleanField(default=True)),
                ('apply_pseudocal', models.BooleanField(default=False)),
                ('debug_mode', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScanParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_mode', models.CharField(choices=[('map', 'Map'), ('linescan', 'Line Scan'), ('point', 'Point')], default='map', max_length=20)),
                ('filename', models.CharField(default='scan', max_length=200)),
                ('acquisition_time', models.FloatField(default=1.0)),
                ('n_frames', models.IntegerField(default=1)),
                ('laser_power', models.FloatField(default=50.0)),
                ('start_position', models.JSONField(default=dict)),
                ('end_position', models.JSONField(default=dict)),
                ('resolution', models.JSONField(default=dict)),
                ('start_wavelength', models.FloatField(default=500.0)),
                ('end_wavelength', models.FloatField(default=600.0)),
                ('wavelength_resolution', models.FloatField(default=1.0)),
                ('polarization_input', models.JSONField(default=dict)),
                ('polarization_output', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='running', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=1)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='scan_data/')),
                ('metadata_file', models.FileField(blank=True, null=True, upload_to='scan_metadata/')),
                ('error_message', models.TextField(blank=True)),
                ('scan_parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raman.scanparameters')),
            ],
        ),
    ]
