from acquisitioncontrol.acqcontrol import AcquisitionControl
from acquisitioncontrol.acqgui import AcquisitionGUI
from acquisitioncontrol.pyqtGUI import MainWindow
# from simulation import DummyMicroscope